# Generated by Django 4.0 on 2021-12-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_unique_id', models.CharField(max_length=255)),
                ('Profile_photo', models.ImageField(null=True, upload_to='images/')),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255, null=True)),
                ('Gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=255, null=True)),
                ('Date_of_Birth', models.DateField(null=True)),
                ('Aadhar_No', models.PositiveIntegerField(null=True)),
                ('Caste', models.CharField(max_length=255, null=True)),
                ('Religion', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('PAN', models.CharField(max_length=25, null=True)),
                ('Date_of_Joining', models.DateField(null=True)),
                ('AICTE_unique_Id', models.CharField(max_length=255, null=True)),
                ('Appointment_type', models.CharField(max_length=255, null=True)),
                ('Cadre', models.CharField(max_length=255, null=True)),
                ('Designation', models.CharField(max_length=255, null=True)),
                ('Specialisation', models.CharField(max_length=250, null=True)),
                ('Department_of_program', models.CharField(max_length=250, null=True)),
                ('Examiner_institution', models.CharField(max_length=250, null=True)),
                ('Area_of_Research', models.CharField(max_length=250, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_no', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
