# Generated by Django 4.0.4 on 2022-06-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_profile_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Aadhar_No',
            field=models.BigIntegerField(null=True),
        ),
    ]
