# Generated by Django 3.2.9 on 2022-07-18 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0013_feedback_feedback_text'),
        ('hod', '0051_auto_20220618_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=256, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hod.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.profile_student')),
            ],
        ),
    ]
