# Generated by Django 3.2.9 on 2022-07-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='status',
            field=models.CharField(default='pending', max_length=256, null=True),
        ),
    ]
