# Generated by Django 3.2.9 on 2022-07-18 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_leave_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='requested_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
