# Generated by Django 3.2.9 on 2022-07-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_leave_request_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='approved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
