# Generated by Django 4.0.5 on 2022-06-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_myuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
