# Generated by Django 3.2.10 on 2021-12-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('date_of_join', models.DateField(null=True)),
                ('semester', models.CharField(max_length=255)),
            ],
        ),
    ]
