# Generated by Django 4.0 on 2021-12-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0004_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='scheme',
            field=models.BigIntegerField(default=2015),
            preserve_default=False,
        ),
    ]
