# Generated by Django 3.2.9 on 2022-03-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0014_auto_20220321_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_to_staff',
            name='subject_id',
            field=models.BigIntegerField(max_length=255),
        ),
    ]
