# Generated by Django 3.2.9 on 2022-03-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0015_alter_subject_to_staff_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_to_staff',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='subject_to_staff',
            name='staff_id',
        ),
    ]
