# Generated by Django 3.2.9 on 2022-03-21 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0016_auto_20220321_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_to_staff',
            name='subject_id',
        ),
    ]
