# Generated by Django 3.2.9 on 2022-03-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0018_auto_20220321_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_to_staff',
            name='subject_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
