# Generated by Django 3.2.9 on 2022-04-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0023_auto_20220426_0640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Internal_mark',
        ),
    ]
