# Generated by Django 3.2.9 on 2022-04-26 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0025_internal_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Internal_mark',
        ),
    ]
