# Generated by Django 3.2.9 on 2022-04-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0027_internal_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance_record',
        ),
    ]
