# Generated by Django 3.2.9 on 2022-04-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0029_attendance_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance_record',
        ),
    ]
