# Generated by Django 3.2.9 on 2022-04-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0030_delete_attendance_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, unique=True)),
                ('marked', models.BooleanField()),
                ('subject_id', models.BigIntegerField()),
                ('batch_id', models.BigIntegerField()),
                ('from_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('no_of_hours', models.BigIntegerField()),
            ],
        ),
    ]
