# Generated by Django 3.2.9 on 2022-04-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0031_attendance_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_record',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
