# Generated by Django 3.2.9 on 2022-04-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0032_alter_attendance_record_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Internal_mark',
        ),
    ]
