# Generated by Django 3.2.9 on 2022-04-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0036_auto_20220428_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='semester',
            field=models.BigIntegerField(),
        ),
    ]
