# Generated by Django 4.0.5 on 2022-07-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0051_auto_20220618_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annoucement_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
