# Generated by Django 3.2.9 on 2022-07-25 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hod', '0052_announcement_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
