# Generated by Django 3.2.9 on 2022-07-12 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20220618_1715'),
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent_profile',
            name='first_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent_profile',
            name='last_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent_profile',
            name='register_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.profile_student'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='parent_student',
        ),
    ]
