# Generated by Django 3.2.9 on 2022-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_alter_parent_profile_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent_profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
