# Generated by Django 4.0 on 2021-12-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(max_length=255)),
                ('university_no', models.BigIntegerField(null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('branch', models.CharField(max_length=255, null=True)),
                ('aadhar_no', models.BigIntegerField(null=True, unique=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('phone_no', models.BigIntegerField(null=True, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Others', 'Others')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('religion', models.CharField(max_length=255, null=True)),
                ('caste', models.CharField(max_length=255, null=True)),
                ('native_place', models.CharField(max_length=255, null=True)),
                ('batch', models.BigIntegerField()),
                ('scheme_id', models.BigIntegerField()),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=10, null=True)),
                ('hobbies', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('sign', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
