# Generated by Django 4.0 on 2021-12-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial_student_final_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_student',
            name='university_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
