# Generated by Django 4.0.4 on 2022-06-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_parents_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='mothers_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
