# Generated by Django 3.2.9 on 2022-07-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='subject_staff',
            new_name='subject_to_staff',
        ),
    ]
