# Generated by Django 3.2.9 on 2022-07-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_rename_student_id_feedback_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_text',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
